<?php
return [
    /*
      |--------------------------------------------------------------------------
      | Incite Web Application Constant
      |--------------------------------------------------------------------------
      |
     */
      'voice_accent' => ['yue-HK','ko-KR','en-AU','id-ID','ta-IN','ja-JP','pt-BR','it-IT','pt-PT','fi-FI','uk-UA','es-ES','ru-RU','en-NG','da-DK','sw','ur-PK','bs','gu-IN','vi-VN','ku','th-TH','hu-HU','la','pl-PL','en-US','ar','ca','en-GB','fr-FR','jv-ID','bn-IN','el-GR','zh-TW','sv-SE','et-EE','ne-NP','tr-TR','es-US','km-KH','hi-IN','cy','su-ID','si-LK','fr-CA','mr-IN','en-IN','sr','sq','cs-CZ','kn-IN','fil-PH','bn-BD','nb-NO','nl-NL','sk-SK','zh-CN','ro-RO','de-DE','ml-IN','te-IN'],
      
      //'voice_accent' => ['ko-KR', 'ru-RU', 'zh-TW', 'hu-HU', 'th-TH', 'nb-NO', 'da-DK', 'tr-TR', 'et-EE', 'bs', 'sw', 'pt-PT', 'vi-VN', 'en-US', 'sv-SE', 'su-ID', 'bn-BD', 'el-GR', 'hi-IN', 'fi-FI', 'km-KH', 'bn-IN', 'fr-FR', 'uk-UA', 'en-AU', 'nl-NL', 'fr-CA', 'sr', 'pt-BR', 'si-LK', 'de-DE', 'ku', 'cs-CZ', 'pl-PL', 'sk-SK', 'fil-PH', 'it-IT', 'ne-NP', 'hr', 'zh-CN', 'es-ES', 'cy', 'ja-JP', 'sq', 'yue-HK', 'en-IN', 'es-US', 'jv-ID', 'la', 'id-ID', 'ro-RO', 'ca', 'ta', 'en-GB'],

      'news_api_language' => [ 
            'en'=>'English',
            'ar'=>'Arabic',
            'de'=>'German',
            'es'=>'Spanish',
            'fr'=>'French',
            'he'=>'Hebrew',
            'it'=>'Italian',
            'nl'=>'Dutch',
            'no'=>'Norwegian',
            'pt'=>'Portuguese',
            'ru'=>'Russian',
            'se'=>'Northern Sami',
            'ud'=>'ud',
            'zh'=>'Chinese'
      ],

      'admin_prefix'=>'admin',

      'font_family' => [ 
            'Times New Roman',
            'serif',
            'Times',
            'Arial',
            'Helvetica',
            'sans-serif',
            'Lucida Console',
            'Courier New',
            'monospace',
            'cursive',
            'Brush Script MT',
      ],

      'speech_lang_code' => [
            'en'=>'en-us',
            'hi'=>'hi-in',
            'ar'=>'ar-eg',
            'bg'=>'bg-bg',
            'bg'=>'cs-cz',
            'nl'=>'nl-be',
            'fr'=>'fr-fr',
            'de'=>'de-de',
            'el'=>'el-gr',
            'es'=>'es-es',
      ],


      'speech_voice' => [
            'Oda'=>'Oda (Female)',
            'Salim'=>'Salim (Male)',
            'Dimo'=>'Dimo (Male)',
            'Rut'=>'Rut (Female)',
            'Luli'=>'Luli (Female)',
            'Shu'=>'Shu (Female)',
            'Chow'=>'Chow (Female)',
            'Wang'=>'Wang (Male)',
            'Jia'=>'Jia (Female)',
            'Xia'=>'Xia (Female)',
            'Chen'=>'Chen (Male)',
            'Akemi'=>'Akemi (Female)',
            'Lin'=>'Lin (Female)',
            'Lee'=>'Lee (Male)',
            'Nikola'=>'Nikola (Male)',
            'Josef'=>'Josef (Male)',
            'Freja'=>'Freja (Female)',
            'Daan'=>'Daan (Male)',
            'Lotte'=>'Lotte (Female)',
            'Bram'=>'Bram (Male)',
            'Zoe'=>'Zoe (Female)',
            'Isla'=>'Isla (Female)',
            'Evie'=>'Evie (Female)',
            'Jack'=>'Jack (Male)',
            'Rose'=>'Rose (Female)',
            'Clara'=>'Clara (Female)',
            'Emma'=>'Emma (Female)',
            'Mason'=>'Mason (Male)',
            'Alice'=>'Alice (Female)',
            'Nancy'=>'Nancy (Female)',
            'Lily'=>'Lily (Female)',
            'Harry'=>'Harry (Male)',
            'Eka'=>'Eka (Female)',
            'Jai'=>'Jai (Female)',
            'Ajit'=>'Ajit (Male)',
            'Oran'=>'Oran (Male)',
            'Linda'=>'Linda (Female)',
            'Amy'=>'Amy (Female)',
            'Mary'=>'Mary (Female)',
            'John'=>'John (Male)',
            'Mike'=>'Mike (Male)',
            'Aada'=>'Aada (Female)',
            'Emile'=>'Emile (Female)',
            'Olivia'=>'Olivia (Female)',
            'Logan'=>'Logan (Female)',
            'Felix'=>'Felix (Male)',
            'Bette'=>'Bette (Female)',
            'Iva'=>'Iva (Female)',
            'Zola'=>'Zola (Female)',
            'Axel'=>'Axel (Male)',
            'Theo'=>'Theo (Male)',
            'Lukas'=>'Lukas (Male)',
            'Hanna'=>'Hanna (Female)',
            'Lina'=>'Lina (Female)',
            'Jonas'=>'Jonas (Male)',
            'Tim'=>'Tim (Male)',
            'Neo'=>'Neo (Male)',
            'Rami'=>'Rami (Male)',
            'Puja'=>'Puja (Female)',
            'Kabir'=>'Kabir (Male)',
            'Mate'=>'Mate (Male)',
            'Intan'=>'Intan (Male)',
            'Bria'=>'Bria (Female)',
            'Mia'=>'Mia (Female)',
            'Pietro'=>'Pietro (Male)',
            'Hina'=>'Hina (Female)',
            'Airi'=>'Airi (Female)',
            'Fumi'=>'Fumi (Female)',
            'Akira'=>'Akira (Male)',
            'Nari'=>'Nari (Female)',
            'Aqil'=>'Aqil (Male)',
            'Marte'=>'Marte (Female)',
            'Erik'=>'Erik (Male)',
            'Julia'=>'Julia (Female)',
            'Jan'=>'Jan (Male)',
            'Marcia'=>'Marcia (Female)',
            'Ligia'=>'Ligia (Female)',
            'Yara'=>'Yara (Female)',
            'Dinis'=>'Dinis (Male)',
            'Leonor'=>'Leonor (Female)',
            'Doru'=>'Doru (Male)',
            'Olga'=>'Olga (Female)',
            'Marina'=>'Marina (Female)',
            'Peter'=>'Peter (Male)',
            'Beda'=>'Beda (Male)',
            'Vid'=>'Vid (Male)',
            'Juana'=>'Juana (Female)',
            'Silvia'=>'Silvia (Female)',
            'Teresa'=>'Teresa (Female)',
            'Jose'=>'Jose (Male)',
            'Camila'=>'Camila (Female)',
            'Sofia'=>'Sofia (Female)',
            'Luna'=>'Luna (Female)',
            'Diego'=>'Diego (Male)',
            'Molly'=>'Molly (Female)',
            'Hugo'=>'Hugo (Male)',
            'Sai'=>'Sai (Male)',
            'Ukrit'=>'Ukrit (Male)',
            'Omer'=>'Omer (Male)',
            'Chi'=>'Chi (Male)',
      ],
];